---
openapi: 3.0.1
info:
  title: Hero API
  version: "1.0"
  description: This API allows CRUD operations on a hero
  contact:
    name: Quarkus
    url: https://github.com/ocp4labs/bbva_ninja/tree/master/chapter_quarkus
servers:
- url: YOUR_ROUTE
paths:
  /api/heroes:
    get:
      responses:
        "204":
          description: No heroes
        "200":
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hero'
          description: OK
      summary: Returns all the heroes from the database
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hero'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
          description: The updated hero
      summary: Updates an exiting  hero
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hero'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URI'
          description: The URI of the created hero
      summary: Creates a valid hero
  /api/heroes/hello:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/String'
          description: OK
  /api/heroes/random:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                description: The hero fighting against the villain
                required:
                - level
                - name
                type: object
                properties:
                  id:
                    format: int64
                    type: integer
                  level:
                    nullable: false
                    format: int32
                    minimum: 1
                    type: integer
                  name:
                    nullable: false
                    maxLength: 50
                    minLength: 3
                    type: string
                  otherName:
                    type: string
                  picture:
                    type: string
                  powers:
                    type: string
          description: OK
      summary: Returns a random hero
  /api/heroes/{id}:
    get:
      parameters:
      - name: id
        description: Hero identifier
        schema:
          $ref: '#/components/schemas/Long'
        in: path
        required: true
      responses:
        "204":
          description: The hero is not found for a given identifier
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
          description: OK
      summary: Returns a hero for a given identifier
    delete:
      parameters:
      - name: id
        description: Hero identifier
        schema:
          $ref: '#/components/schemas/Long'
        in: path
        required: true
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
      summary: Deletes an exiting hero
  /api/heroes/{nombre}:
    get:
      parameters:
      - examples:
          Nombre:
            value: Batman
        name: nombre
        schema:
          type: string
        in: path
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
              examples:
                Example Hero:
                  value: {}
          description: 200 OK
components:
  schemas:
    Hero:
      description: The hero fighting against the villain
      required:
      - level
      - name
      type: object
      properties:
        id:
          format: int64
          type: integer
        level:
          nullable: false
          format: int32
          minimum: 1
          type: integer
        name:
          nullable: false
          maxLength: 50
          minLength: 3
          type: string
        otherName:
          type: string
        picture:
          type: string
        powers:
          type: string
    URI:
      type: object
      properties:
        string:
          type: string
        rawAuthority:
          type: string
        rawFragment:
          type: string
        rawPath:
          type: string
        rawQuery:
          type: string
        rawSchemeSpecificPart:
          type: string
        rawUserInfo:
          type: string
        absolute:
          type: boolean
        opaque:
          type: boolean
    Long:
      format: int64
      type: integer
    String:
      type: string
tags:
- name: api
  description: Public that can be used by anybody
- name: heroes
  description: Anybody interested in heroes
externalDocs:
  description: All the Quarkus workshops
  url: https://github.com/ocp4labs/bbva_ninja/tree/master/chapter_quarkus
